practice spawns
FortressOne/server-qwprogs pull request #747
Opened 2022-02-04 08:34 UTC by evilantAU

2022-02-04 08:34 UTC, evilantAU commented
practice spawns

2022-02-04 09:03 UTC, drzel requested changes
It's mostly fine, and I like the feature a lot, a few small requests:

- Instead of suicide time penalties removed, can we just have another localinfo to set the penalty length?
- Indents are all out, there's a few places where it's actually reversed, could you fix that up?
- There's a merge conflict with the readme that needs to be fixed.

2022-02-04 09:03 UTC, drzel commented on ssqc/client.qc
> +	self.suicide_time = time;
indent seems broken here

2022-02-04 09:03 UTC, drzel commented on ssqc/client.qc
> +		return spot2;
also here should be across one

2022-02-04 12:15 UTC, lordee commented on ssqc/client.qc
> +	self.suicide_time = time;
What's the thinking for yet another setting for suicide time for practice spawns? Seems like a lot of bloat and configuration for no reason

2022-02-04 12:16 UTC, lordee commented on ssqc/client.qc
> +		return spot2;
Can't see the issue here?

2022-02-05 12:40 UTC, lordee commented on ssqc/client.qc
> +		return spot2;
I can in desktop mode actually... yeah needs an indent

2022-02-06 10:30 UTC, merged