Grenade ping correction
FortressOne/server-qwprogs pull request #877
Opened 2022-09-15 09:12 UTC by newbytf

Due to their <prime> <wait> <throw> nature, grenades have all sorts of
inconsistencies introduced by delay between client and server around
each event.

Two players that see each other at the same time, and prime at the same
time, will actually not be able to throw at the same time as the
player with the lower ping is able to get the server to register their
prime first.

This is particularly material since grenades don't allow you to throw
for the first 800ms, so even 50-100ms ping differences are a large
relative advantage.

This introduces ping correction, so that the point at which we consider
the client to have primed is corrected for their latency when enabled.
We ensure that this does not let players prime any faster, or more
frequently, than they would have been able to before, only more
consistently.

One very nice property is that unlike projectile projection, which
causes visible projectiles to skip, there are no strange artifacts for
other clients as the adjustment occurs before it's possible to throw the
grenade.

Also rewrite the grenade timer rendering client code to be more compact
and to handle the fact that the expiry offset has been adjusted to
correct for latency.

Clients that do not support CSQC can simply playsound at the point which
they prime; this will now be correctly aligned (as the point they primed
is properly reflected to the server).

Controlled by:
  localinfo precise_grenades on/off

While we'd normally default a server setting on, this is a big enough
change that we'll give it a pug or two of testing before pushing it as a
default to soak.  [For this reason we also temporarily allow mid-round
changing of the tunable.]

2022-09-15 14:33 UTC, drzel requested changes
This branch doesn't compile for me presently:
```
~/Workspace/FortressOne/server-qwprogs((HEAD detached at newbytf/gren_dev1))$ make
fteqcc64 -DVER=\"r37fa597~37fa597\" -DREV=\"37fa597\" ./ssqc/progs.src
FTEQCC: git-250a5af6 (%cs)
Source file: ./ssqc/progs.src
Outputfile: ./ssqc/../qwprogs.dat
including ./ssqc/../share/fteextensions.qc
including ./ssqc/defs.qc
including ./ssqc/../share/commondefs.qc
including ./ssqc/../share/common_helpers.qc
including ./ssqc/qw.qc
including ./ssqc/events.qc
including ./ssqc/roles.qc
including ./ssqc/q3defs.qc
including ./ssqc/debug.qc
including ./ssqc/status.qc
including ./ssqc/functions.qc
including ./ssqc/menu.qc
including ./ssqc/csmenu.qc
including ./ssqc/../share/common_vote.qc
including ./ssqc/vote.qc
including ./ssqc/extraents.qc
including ./ssqc/help.qc
including ./ssqc/subs.qc
including ./ssqc/combat.qc
including ./ssqc/items.qc
including ./ssqc/locfiles.qc
including ./ssqc/antilag.qc
including ./ssqc/weapons.qc
including ./ssqc/world.qc
including ./ssqc/client.qc
including ./ssqc/player.qc
including ./ssqc/doors.qc
including ./ssqc/buttons.qc
including ./ssqc/triggers.qc
including ./ssqc/tforttm.qc
including ./ssqc/plats.qc
including ./ssqc/misc.qc
including ./ssqc/monsters.qc
including ./ssqc/flare.qc
including ./ssqc/sentry.qc
including ./ssqc/boss.qc
including ./ssqc/admin.qc
including ./ssqc/scout.qc
including ./ssqc/sniper.qc
including ./ssqc/tsoldier.qc
including ./ssqc/demoman.qc
including ./ssqc/medic.qc
including ./ssqc/hwguy.qc
including ./ssqc/pyro.qc
including ./ssqc/spy.qc
including ./ssqc/engineer.qc
including ./ssqc/camera.qc
including ./ssqc/clan.qc
including ./ssqc/quadmode.qc
including ./ssqc/tfort.qc
including ./ssqc/tforthlp.qc
including ./ssqc/tfortmap.qc
including ./ssqc/login.qc
including ./ssqc/commands.qc
including ./ssqc/ctf.qc
including ./ssqc/coop.qc
including ./ssqc/actions.qc
including ./ssqc/spect.qc
including ./ssqc/q3.qc
including ./ssqc/mvdsv.qc
including ./ssqc/rotate.qc
including ./ssqc/fo_logic.qc
including ./ssqc/fo_math.qc
including ./ssqc/fo_misc_info.qc
./ssqc/qw.qc:602: warning Q302: float project_grenades  no references.
Compile finished: ./ssqc/../qwprogs.dat (fte format)
Done. 1 warnings
fteqcc64 -DVER=\"r37fa597~37fa597\" -DREV=\"37fa597\" ./csqc/csprogs.src
FTEQCC: git-250a5af6 (%cs)
Source file: ./csqc/csprogs.src
Outputfile: ./csqc/../csprogs.dat
including ./csqc/csdefs.qc
including ./csqc/csextradefs.qc
including ./csqc/../share/commondefs.qc
including ./csqc/../share/common_helpers.qc
including ./csqc/../share/common_vote.qc
including ./csqc/sui_sys.qc
including ./csqc/vote.qc
including ./csqc/status.qc
including ./csqc/menu.qc
including ./csqc/main.qc
including ./csqc/events.qc
in function ParseGrenPrimed (line 343),
./csqc/events.qc:361: warning F306: Local "ParseSBAR" hides global with same name and type
./csqc/events.qc:1:    const void() ParseSBAR is defined here
./csqc/events.qc:456: warning F306: Local "CSQC_Event_Sound" hides global with same name and type
./csqc/csdefs.qc:156:    const float(float entnum, float channel, string soundname, float vol, float attenuation, vector pos, float pitchmod) CSQC_Event_Sound is defined here
./csqc/events.qc:477: error: unexpected EOF
including ./csqc/hud_helpers.qc
including ./csqc/hud.qc
including ./csqc/settings.qc
including ./csqc/input.qc

************ ERROR ************
Errors have occured
Error in ./csqc/events.qc on line 477
make: *** [Makefile:11: all] Error 1
```

2022-09-16 04:47 UTC, newbytf commented
Rebased for conflicts

2022-09-16 06:14 UTC, drzel requested changes
Seems to be some stuff bleeding through when changes are disabled at the moment. To reproduce:

Settings:
- `localinfo project_grenades off`
- `fo_grentype 2`
- `cl_delay_packets 500`

Steps:
- Compile and run on master
- Prime a grenade and grenade jump, feels fine.
- Compile and run on this branch.
- Prime a grenade and grenade jump, grenade explodes significantly before expected from timer.

This PR shouldn't cause any changes with those settings right?

2022-09-16 06:18 UTC, newbytf commented
To confirm when you say localinfo, you mean set on server and not client?  It would not do anything client side.

2022-09-16 06:18 UTC, drzel commented
That's right, `rcon localinfo project_grenades off`.

2022-09-16 06:29 UTC, drzel commented
https://youtu.be/KqKy0DBOefA

2022-09-16 07:14 UTC, newbytf commented
Ah, I think I see the difference.  I offset the sound file for the rtt/2 throw time but intentionally not the rendered timer, since that way it ticks to zero the same time you see the grenade explode.  E.g. it's reflecting the world as you see it vs auditory being signal to send.

The old code also adjusted the rendered timer.  
There are arguments for either, but no reason not to be consistent with prior behavior.  I'll apply the offset and things should line up again.

2022-09-16 07:15 UTC, newbytf commented
(Note I actually prefer offsetting the visual timer so that you can key throws off its ticks as well.  I actually misremembered and thought the old code had done this, could have saved myself typing since it's simpler not to separate; I was separating in the name of what I thought was maintaining behavior :-)

2022-09-16 09:07 UTC, newbytf commented
Ok, updated to factor the adjustment into the rendered timer also.  For high pings the new timers are 100-200 ms different from the old timers sometimes.  I've verified however that this is the new timers being "more correct" when this occurs (explodes_at returned by server is more accurate than guessing it from when we got a prime message).  This drift on the old timers (and the error it incurred) is much lower at more reasonable e.g. 10-100ms ping values vs the 500 I was testing at.

Might feel very slightly different for a game or two, but should ultimately be just better.

2022-09-16 11:09 UTC, drzel commented on csqc/csextradefs.qc
> +    float grentype_;
Curious - what is the significance of the trailing underscore?

2022-09-16 11:43 UTC, drzel reviewed
A couple of questions from looking at the code, I haven't had a chance to test it yet:
- Is there some technical reason why we can't we keep the existing logic and have the new logic as an option?
- If a 500ms ping and 0ms ping player are dueling, and are using autoprime, am I correct that the hpb's gren will explode earlier than the 0 ping player?

2022-09-16 17:38 UTC, newbytf commented
> A couple of questions from looking at the code, I haven't had a chance to test it yet:
> 
> * Is there some technical reason why we can't we keep the existing logic and have the new logic as an option?

A) Yes, when ping correction is enabled the expiry is no longer relative to the time we receive the grenade primed message.
B) The new message allows you to directly compare the accuracy of all approaches since it includes the server prime and expiration time.  In all cases either i) the new and old timers align exactly or ii) the new timers are correct and the old timers are not due to asymmetries in RTT or jitter.  The old mode could literally be emulated by adding a random number that's a function of RTT.  This is a strict improvement.



> * If a 500ms ping and 0ms ping player are dueling, and are using autoprime, am I correct that the hpb's gren will explode earlier than the 0 ping player?

I didn't realize duel mode had added this.  Yes, server generated primes need to not be corrected.  Added handling for this.

2022-09-16 17:48 UTC, newbytf commented on csqc/csextradefs.qc
> +    float grentype_;
All quakec class members are explicitly private, this is a common naming convention reflecting that.  It both helps to recognize when you're dealing with a member variable (versus say a local or global) and ensures we avoid naming collisions with accessor-functions when defined.

2022-09-17 05:50 UTC, drzel commented
Seems like this is still broken, actually with both `fo_grentype 2` and `fo_grentype 3`.

The audio and visual timers appear desynced, and oddly the amount of drift seems to be variable.

At a higher level, what's keeping me from merging this right now is that it's breaking existing behaviour without project_weapons set. I think you have three things going on here:
- Refactor (great!)
- New feature (great!)
- Proposed bug fix for existing behaviour (needs attention).

From my testing presently the bug is fix is introducing a bug, not resolving an existing one. I don't want to stand in your way, but I don't want to break things for existing players. Can we please leave the existing logic and behavior and add the new logic and behaviour behind a setting?

To replicate my concerns, turn off project_grenades, set `cl_delay_packets 500` and try to grenade jump using the audio timer. Do this multiple times. Observe the variable desync between audio and video timer, and the seemingly early grenade explode.

Specifically, while you're saying the ungated changes are strictly an improvement, my testing is showing this isn't the case and that in it's current form it's broken.

2022-09-17 08:07 UTC, newbytf commented
So the problem here turned out to be soundupdate.

It specifies that "changes the properties of the current sound being played on the given entity channel. newsample may be empty, and will be ignored in this case. timeoffset is relative to the current position (subtract the result of getsoundtime for absolute positions).", e.g. that we can pass an empty newsample to adjust the offset of the sound playing on the channel.

This turns out not to be true.  In my testing I was looking at all of the values rather than listening to the sound (e.g. the programmed expiry time and the offset passed to the timer).

With soundupdate fixed the sound is also correct and should now work for you.

Relative to the existing behavior, if you look at the debug prints you will see this is a bug fix.  It is always the same value, or more accurate.  It's also not possible to use the prior behavior with a server adjusted expiry, as you do not know what offset to adjust for. Hopefully, with the sound fixed that is no longer an issue.

2022-09-17 08:12 UTC, newbytf commented
You can set fo_grentimer_debug 1 on the new patch to see where the old timer was occasionally inconsistent, that the new timers are more correct on.  (As above, problem was sound builtin turned out to be completely ignoring that offset which is why it felt so off, it was always 0.)

2022-09-17 11:03 UTC, drzel commented
Okay awesome, I'll look at this ASAP. In the meantime, as a general preference I'd prefer new commits as you get feedback rather than rebasing and force pushing, since it lets me view the diff between each change.

2022-09-17 14:58 UTC, drzel commented
Okay nice! Seems good for staging. Just briefly hopped around but didn’t detect any issues. Computer packed up back in a couple of days. Maybe make an announcement when you can.

2022-09-17 14:58 UTC, merged